In [1]:
import pandas as pd

path = "/home/565/pv3484/aus_substation_electricity/data/BOM_NSW_weather_processed_v1/BOM_NSW_weather_master.csv"

df = pd.read_csv(path)
df.head()

/jobfs/162980332.gadi-pbs/ipykernel_2737977/3632518375.py:5: DtypeWarning: Columns (0,1,3,4,5,6,7,9,10,11,12,13,15,16,17,18,20,21,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,datetime_local,station_id,temp,rh,wind_speed,wind_dir,rain_obs
0,hm,",",61055.0,",",01/01/2003 11:00,",",01/01/2003 00:00,",",0.0,",",...,NaN,0.0,",",2003-01-01 11:00:00,61055.0,NaN,NaN,NaN,NaN,NaN
1,hm,",",61055.0,",",01/01/2003 11:30,",",01/01/2003 00:30,",",0.0,",",...,NaN,0.0,",",2003-01-01 11:30:00,61055.0,NaN,NaN,NaN,NaN,NaN
2,hm,",",61055.0,",",01/01/2003 12:00,",",01/01/2003 01:00,",",0.0,",",...,19.0,0.0,",",2003-01-01 12:00:00,61055.0,NaN,NaN,NaN,NaN,NaN
3,hm,",",61055.0,",",01/01/2003 12:30,",",01/01/2003 01:30,",",0.0,",",...,22.0,0.0,",",2003-01-01 12:30:00,61055.0,NaN,NaN,NaN,NaN,NaN
4,hm,",",61055.0,",",01/01/2003 13:00,",",01/01/2003 02:00,",",0.0,",",...,19.0,0.0,",",2003-01-01 13:00:00,61055.0,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd

path = "/home/565/pv3484/aus_substation_electricity/data/BOM_NSW_weather_processed_v3/weather_station_061055.csv"

df_1 = pd.read_csv(path)

df_1.head()

,timestamp_utc,temp,dewpoint,relative_humidity,wind_speed_kmh,wind_direction_deg,precip_incremental,lat,lon,station_name,station_id
0,2003-01-01 00:00:00+00:00,24.3,17.1,64.0,0.0,0.0,0.0,-32.9184,151.7985,NEWCASTLE NOBBYS SIGNAL STATION AWS,61055
1,2003-01-01 00:30:00+00:00,25.3,17.5,62.0,0.0,0.0,0.0,-32.9184,151.7985,NEWCASTLE NOBBYS SIGNAL STATION AWS,61055
2,2003-01-01 01:00:00+00:00,22.0,17.0,73.0,22.3,190.0,0.0,-32.9184,151.7985,NEWCASTLE NOBBYS SIGNAL STATION AWS,61055
3,2003-01-01 01:30:00+00:00,23.6,16.9,66.0,22.3,220.0,0.0,-32.9184,151.7985,NEWCASTLE NOBBYS SIGNAL STATION AWS,61055
4,2003-01-01 02:00:00+00:00,22.1,17.1,73.0,13.0,190.0,0.0,-32.9184,151.7985,NEWCASTLE NOBBYS SIGNAL STATION AWS,61055