# Looking at the new demand data sets (QLD)

## Energex

In [4]:
import pandas as pd

path = "/g/data/ng72/pv3484/substation_data/raw_data/QLD_demand/Energex_QLD/collated_deduplicated_energex_2010_mw_30min.csv"
df = pd.read_csv(path)

df.head()          # first 5 rows
#df.columns         # all column names
#df.columns[:10]    # first 10 column names

,StartDeliveryTime,EndDeliveryTime,UtilityName,'ABY'|'Amberley'|ActivePower,'ACR'|'Albany Creek'|ActivePower,'AGE'|'Ashgrove'|ActivePower,'AGT'|'Algester'|ActivePower,'AHD'|'Alexandra Headland'|ActivePower,'AHL'|'Arana Hills'|ActivePower,'ALY'|'Annerley'|ActivePower,...,'WFD'|'Woodford'|ActivePower,'WHO'|'Wivenhoe'|ActivePower,'WMD'|'West Maroochydore'|ActivePower,'WNM'|'Wynnum'|ActivePower,'WRD'|'Wellington Rd'|ActivePower,'WRG'|'Woodridge'|ActivePower,'WSO'|'Wacol South'|ActivePower,'YDA'|'Yandina'|ActivePower,'YTA'|'Yatala'|ActivePower,'ZMR'|'Zillmere'|ActivePower
0,2010-01-01 00:00:00,2010-01-01 00:30:00,Energex,0.738769,11.37500,9.98438,6.62720,31.6406,14.2539,9.62573,...,3.92578,1.51904,14.9590,10.78130,24.3083,13.7227,2.62915,NaN,13.3630,12.9063
1,2010-01-01 00:30:00,2010-01-01 01:00:00,Energex,0.695312,10.78130,9.75000,6.21435,30.6250,13.7107,8.97388,...,3.82910,1.38208,14.2273,10.56640,24.2542,13.2070,2.69434,NaN,12.8850,12.6563
2,2010-01-01 01:00:00,2010-01-01 01:30:00,Energex,0.717041,9.67188,9.25000,5.80151,29.6680,12.0811,9.10425,...,4.06933,1.48584,13.7124,9.66797,23.6580,12.7266,2.56396,NaN,12.2983,11.5469
3,2010-01-01 01:30:00,2010-01-01 02:00:00,Energex,0.673584,8.60938,8.68750,5.49731,27.9297,10.9294,8.77832,...,3.77637,1.29492,12.7368,8.96484,23.1702,12.4746,2.36841,NaN,11.5161,10.8438
4,2010-01-01 02:00:00,2010-01-01 02:30:00,Energex,0.630126,7.82813,8.21875,5.25830,26.4648,10.3210,8.43066,...,3.54199,1.19946,12.1948,8.80859,22.7366,12.1523,2.25976,NaN,10.8425,10.6250

In [11]:
import pandas as pd

path = "//g/data/ng72/pv3484/substation_data/raw_data/VIC_demand/Jemena_VIC/collated_deduplicated_jemena_2013_mw_30min.csv"
df = pd.read_csv(path)

df.head()          # first 5 rows
#df.columns         # all column names
#df.columns[:10]    # first 10 column names

,StartDeliveryTime,EndDeliveryTime,UtilityName,'AW'|'Airport West Zone Substation'|ActivePower,'BY'|'Braybrook Zone Substation'|ActivePower,'CN'|'Coburg North Zone Substation'|ActivePower,'COO'|'Coolaroo Zone Substation'|ActivePower,'CS'|'Coburg South Zone Substation'|ActivePower,'ES'|'Essendon Zone Substation'|ActivePower,'FE'|'Footscray East Zone Substation'|ActivePower,...,'NH'|'North Heidelberg Zone Substation'|ActivePower,'NS'|'North Essendon Zone Substation'|ActivePower,'NT'|'Newport Zone Substation'|ActivePower,'P'|'Preston Zone Substation'|ActivePower,'PV'|'Pascoe Vale Zone Substation'|ActivePower,'SBY'|'Pascoe Vale Zone Substation'|ActivePower,'SHM'|'Sydenham Zone Substation'|ActivePower,'ST'|'Somerton Zone Substation'|ActivePower,'TH'|'Tottenham Zone Substation'|ActivePower,'YVE'|'Yarraville Zone Substation'|ActivePower
0,2013-01-01 00:00:00,2013-01-01 00:30:00,Jemena,30.5,9.7,24.2,13.5,15.7,10.1,9.7,...,19.2,9.4,13.2,3.2,10.5,10.9,13.0,25.1,6.6,8.2
1,2013-01-01 00:30:00,2013-01-01 01:00:00,Jemena,29.4,9.5,23.9,12.8,15.1,9.6,9.3,...,18.4,9.0,12.5,3.1,9.9,10.5,12.3,24.7,6.6,7.7
2,2013-01-01 01:00:00,2013-01-01 01:30:00,Jemena,28.3,9.4,23.2,12.8,14.4,9.2,8.8,...,17.6,8.5,12.4,3.0,9.4,9.9,12.3,24.1,6.7,7.5
3,2013-01-01 01:30:00,2013-01-01 02:00:00,Jemena,27.4,9.1,22.4,12.7,13.8,8.9,8.6,...,17.0,8.1,11.7,3.1,8.9,9.2,12.0,24.6,6.5,7.3
4,2013-01-01 02:00:00,2013-01-01 02:30:00,Jemena,26.7,8.7,21.8,12.3,13.8,8.6,8.7,...,17.0,7.9,11.6,3.1,8.5,9.2,11.5,24.3,6.3,8.2

In [3]:
import pandas as pd

path = "/g/data/ng72/pv3484/substation_data/DNSP_Zone_Substation_Characteristics.csv"
df = pd.read_csv(path)

df.tail(30)

,Distribution Network Service Provider,energy_asset,Zone Substation Name,Zone Substation ID,Zone Substation Area (km2),Dwellings,Persons,Residential,Commercial,Industrial,Primary Production,Education,Hospital/Medical,Transport,Parkland,Water,Other
1268,Western Power,WP_MYR,Myaree,MYR,12,10746,25037,0.770,0.041,0.000,0.000,0.038,0.000,0.000,0.151,0.000,0.000
1269,Western Power,WP_N,Nedlands,N,8,5721,13558,0.737,0.038,0.006,0.000,0.025,0.014,0.010,0.162,0.007,0.000
1270,Western Power,WP_NB,North Beach,NB,25,15979,40734,0.662,0.012,0.000,0.000,0.037,0.001,0.020,0.268,0.000,0.000
1271,Western Power,WP_NF,North Fremantle,NF,5,2893,5234,0.296,0.080,0.084,0.000,0.005,0.000,0.033,0.495,0.000,0.008
1272,Western Power,WP_NGN,Narrogin,NGN,7284,4274,9072,0.004,0.000,0.000,0.841,0.000,0.000,0.000,0.139,0.002,0.013
1273,Western Power,WP_NOR,Northam,NOR,4653,8463,16975,0.024,0.000,0.000,0.933,0.000,0.000,0.000,0.021,0.000,0.020
1274,Western Power,WP_NP,North Perth,NP,12,15163,32205,0.705,0.072,0.023,0.000,0.018,0.000,0.017,0.109,0.056,0.000
1275,Western Power,WP_OC,O Connor,OC,18,12021,28706,0.644,0.042,0.079,0.000,0.029,0.000,0.000,0.198,0.009,0.000
1276,Western Power,WP_OP,Osborne Park,OP,8,4608,10214,0.480,0.065,0.327,0.000,0.002,0.021,0.000,0.101,0.004,0.000
1277,Western Power,WP_PBY,Padbury,PBY,32,22779,57799,0.732,0.015,0.000,0.000,0.035,0.000,0.025,0.192,0.000,0.000
1278,Western Power,WP_PCY,Piccadilly,PCY,36,10878,25022,0.449,0.051,0.017,0.258,0.020,0.003,0.006,0.196,0.000,0.000
1279,Western Power,WP_PIC,Picton,PIC,643,9895,24749,0.045,0.000,0.035,0.758,0.001,0.000,0.000,0.144,0.001,0.014
1280,Western Power,WP_PNJ,Pinjarra,PNJ,855,3864,9246,0.033,0.000,0.002,0.293,0.000,0.000,0.000,0.665,0.006,0.000
1281,Western Power,WP_RAN,Rangeway,RAN,23,7730,17001,0.535,0.003,0.074,0.178,0.030,0.001,0.027,0.152,0.000,0.000
1282,Western Power,WP_RO,Rockingham,RO,38,19349,39821,0.454,0.039,0.094,0.000,0.032,0.005,0.006,0.312,0.012,0.046
1283,Western Power,WP_RTN,Riverton,RTN,27,20483,52863,0.760,0.030,0.014,0.000,0.038,0.000,0.003,0.156,0.000,0.000
1284,Western Power,WP_RVE,Rivervale 132kV,RVE,11,11823,23770,0.610,0.129,0.000,0.000,0.020,0.000,0.026,0.215,0.000,0.000
1285,Western Power,WP_SNR,Southern River,SNR,91,22273,62013,0.641,0.006,0.030,0.082,0.014,0.002,0.000,0.178,0.000,0.046
1286,Western Power,WP_SP,Shenton Park,SP,11,4653,9487,0.235,0.010,0.046,0.000,0.104,0.066,0.010,0.424,0.000,0.104
1287,Western Power,WP_SVY,Sawyers Valley,SVY,398,4813,12462,0.205,0.000,0.002,0.184,0.001,0.000,0.000,0.298,0.000,0.310
1288,Western Power,WP_TT,Tate St,TT,11,9051,20021,0.550,0.071,0.273,0.000,0.027,0.012,0.000,0.066,0.000,0.000
1289,Western Power,WP_WAI,Waikiki,WAI,62,22372,59542,0.601,0.008,0.019,0.000,0.021,0.000,0.002,0.321,0.005,0.024
1290,Western Power,WP_WD,Wembley Downs,WD,25,9935,25536,0.432,0.000,0.016,0.000,0.045,0.000,0.017,0.470,0.009,0.010
1291,Western Power,WP_WE,Welshpool,WE,39,15871,39847,0.617,0.043,0.181,0.000,0.017,0.000,0.013,0.129,0.000,0.000
1292,Western Power,WP_WGA,Wangara,WGA,27,2414,6545,0.092,0.000,0.229,0.007,0.001,0.000,0.000,0.126,0.000,0.544
1293,Western Power,WP_WLN,Willetton,WLN,10,5639,16687,0.650,0.085,0.090,0.000,0.044,0.000,0.000,0.132,0.000,0.000
1294,Western Power,WP_WNO,Wanneroo,WNO,148,18340,48898,0.121,0.007,0.020,0.006,0.007,0.001,0.000,0.695,0.006,0.135
1295,Western Power,WP_WUN,Wundowie,WUN,919,2308,6989,0.097,0.000,0.001,0.574,0.000,0.000,0.000,0.274,0.000,0.054
1296,Western Power,WP_Y,Yokine,Y,19,22684,45509,0.753,0.020,0.023,0.000,0.029,0.000,0.000,0.175,0.000,0.000
1297,Western Power,WP_YP,Yanchep,YP,458,13657,33365,0.108,0.001,0.002,0.161,0.001,0.000,0.000,0.561,0.005,0.161